### ISSUE TITLE
Images not loading via Aggregator

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#124]
Events being loaded by Aggregator are missing images.

Example: https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/6673508cca2fdb0064cec7b8

This event should be loading the image from 
http://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fzones-musicales-lucibela.aspx%232024-07-19

This is the call to Artsdata API to get the data for this event
https://api.artsdata.ca/query?frame=event_footlight&format=json&sparql=https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/sparql/query-event-uri-v2.sparql&uri=https://www.laval.ca/Pages/Fr/Calendrier/zones-musicales-lucibela.aspx%232024-07-19&source=http://kg.artsdata.ca/culture-creates/artsdata-planet-ville-de-laval/calendrier-activites

**Comment by dev-aravind** [comment]
@saumier This was caused by aggregator not being configured to handle our image gallery feature. The issue is fixed and up in production right now. The images will load now when aggregator runs the next time (I already ran the ville de laval aggregator to test the event mentioned above). Please review this and let me know if you find any issues.
